#ifndef TYPY_WYLICZENIOWE_HPP_
#define TYPY_WYLICZENIOWE_HPP_

enum KODY_WYJSCIOWE {OK=0, BRAK_PORTU, BLAD_PORTU, NIE_WYBRANO_PORTU, BRAK_NAZWY_PLIKU, BLAD_PLIKU, ZAMKNIETO_PLIK, NIE_ZAMKNIETO_PLIKU, BLAD_OTWARCIA_PLIKU, OTWARTO_PLIK};
enum STANY_MASZYNY {BRAK_ROZKAZU=0, CZEKAJ, USTAW_TEMPERATURE, SREDNIA_TEMPERATURA, TEMPERATURA_DOCELOWA, RESTART};

#endif
