#ifndef TYPY_WYLICZENIOWE_HPP_
#define TYPY_WYLICZENIOWE_HPP_

enum KODY_WYJSCIOWE {OK=0,BRAK_PORTU,BLAD_PORTU,NIE_WYBRANO_PORTU,BRAK_NAZWY_PLIKU,BLAD_PLIKU};
enum STANY_MASZYNY {BRAK_ROZKAZU=0,CZEKAJ,USTAW_TEMPERATURE,SREDNIA_TEMPERATURA,TEMPERATURA_DOCELOWA,RESTART};

#endif
