#ifndef TYPY_WYLICZENIOWE_HPP_
#define TYPY_WYLICZENIOWE_HPP_

enum KODY_WYJSCIOWE {OK=0,BRAK_PORTU=1,BLAD_PORTU=2,BRAK_NAZWY_PLIKU=3,BLAD_PLIKU=4};
enum STANY_MASZYNY {BRAK_ROZKAZU=0,CZEKA=1,USTAWIA_TEMPERATURE=2};

#endif
